Repository CDCgov/RecordLinker, pull requests merged in 2024-12, with the labels that each got.

#125 Identifier Triplets RFC-001
  rfc/000-template.md
  rfc/001-identifier-triplets.md
Labels: documentation

#145 bootstap script
  .env
  .gitignore
  README.md
  pyproject.toml
  scripts/bootstrap.sh
  src/recordlinker/config.py
  src/recordlinker/database/__init__.py
  tests/unit/database/test_base.py
Labels: automation

#123 NBS Test Cases
  .gitignore
  compose.yml
  tests/algorithm/Dockerfile.algo
  tests/algorithm/README.md
  tests/algorithm/algo.env
  tests/algorithm/configurations/algorithm_configuration.json
  tests/algorithm/data/sample_seed_data.csv
  tests/algorithm/data/sample_test_data.csv
  tests/algorithm/scripts/helpers.py
  tests/algorithm/scripts/reset_db.py
  tests/algorithm/scripts/run_test.py
  tests/algorithm/scripts/seed_db.py
  tests/algorithm/scripts/send_test_records.py
  tests/algorithm/scripts/set_configuration.py
Labels: qa

#150 Fix: pin pythonjsonlogger to 2.X.X
  pyproject.toml
Labels: bug

#151 Fix: adding DB_URI var when building docs in release
  .github/workflows/release.yml
Labels: bug
