Repository CDCgov/RecordLinker, pull requests merged in 2024-10, with the labels that each got.

#52 Implementation of linkage algorithm against new schema
  assets/linking/basic_algorithm.json
  assets/linking/enhanced_algorithm.json
  src/recordlinker/linkage/matchers.py
  src/recordlinker/linkage/simple_mpi.py
  src/recordlinker/linking/link.py
  src/recordlinker/linking/matchers.py
  src/recordlinker/models/__init__.py
  src/recordlinker/models/mpi.py
  src/recordlinker/models/pii.py
  tests/unit/linking/test_link.py
  tests/unit/linking/test_matchers.py
  tests/unit/linking/test_mpi_service.py
  tests/unit/models/test_mpi.py
  tests/unit/models/test_pii.py
  tests/unit/test_matchers.py
Labels: enhancement

#61 Add Address feature for comparisons
  src/recordlinker/linking/link.py
  src/recordlinker/linking/matchers.py
  src/recordlinker/models/mpi.py
  src/recordlinker/models/pii.py
  tests/unit/models/test_mpi.py
  tests/unit/models/test_pii.py
Labels: enhancement

#54 Feat/algo config api update
  alembic/versions/a30b8bbccfdf_add_dibbs_algorithms.py
  pyproject.toml
  src/recordlinker/linking/algorithm_service.py
  src/recordlinker/linking/mpi_service.py
  src/recordlinker/main.py
  src/recordlinker/utils.py
  tests/unit/linking/test_algorithm_service.py
  tests/unit/test_record_linkage.py
Labels: enhancement

#66 updating link-record endpoint to use either schema
  compose.yml
  pyproject.toml
  src/recordlinker/config.py
  src/recordlinker/database.py
  src/recordlinker/linking/link.py
  src/recordlinker/linking/mpi_service.py
  src/recordlinker/main.py
  src/recordlinker/models/__init__.py
  src/recordlinker/models/base.py
  tests/performance/rlpt.env
  tests/performance/scripts/send_linkage_requests.sh
  tests/performance/scripts/test_synthea_data.sh
  tests/unit/linking/test_mpi_service.py
Labels: enhancement

#73 Adding MPI design document
  README.md
  docs/mpi-design.md
  docs/policies/CONTRIBUTING.md
  docs/policies/DISCLAIMER.md
  docs/policies/code-of-conduct.md
  docs/policies/open_practices.md
  docs/policies/rules_of_behavior.md
  docs/policies/thanks.md
Labels: documentation

#70 RL-56 MyPy Github Action and script for type checks
  .github/workflows/check_types.yml
  pyproject.toml
  scripts/check_types.sh
  src/recordlinker/base_service.py
  src/recordlinker/linking/algorithm_service.py
  src/recordlinker/linking/mpi_service.py
Labels: ops

#72 Update to use algo object
  alembic/versions/a30b8bbccfdf_add_dibbs_algorithms.py
  codecov.yml
  src/recordlinker/linking/link.py
  src/recordlinker/linking/mpi_service.py
  src/recordlinker/main.py
  src/recordlinker/models/algorithm.py
  tests/unit/conftest.py
  tests/unit/linking/test_link.py
  tests/unit/linking/test_mpi_service.py
  tests/unit/models/test_mpi.py
  tests/unit/test_main.py
Labels: enhancement

#74 adding titles to the PR slack notifications
  .github/CODEOWNERS
  .github/workflows/slack_notifier_merged.yaml
  .github/workflows/slack_notifier_review.yaml
Labels: enhancement

#77 Optimizing initialization of evaluators and rule
  src/recordlinker/linking/link.py
  src/recordlinker/models/algorithm.py
  src/recordlinker/utils.py
  tests/unit/models/test_algorithm.py
  tests/unit/test_utils.py
Labels: enhancement

#78 CI workflow to post open PRs to slack
  .github/codecov.yml
  .github/workflows/slack_notifier_merged.yml
  .github/workflows/slack_notifier_open_pulls.yml
  .github/workflows/slack_notifier_review.yml
  scripts/open_pulls.sh
Labels: enhancement

#79 New Link API Endpoint
  .github/codecov.yml
  alembic/versions/fb1b1ba0ad1f_add_reference_id_to_person_and_patient.py
  src/recordlinker/linking/link.py
  src/recordlinker/main.py
  src/recordlinker/models/mpi.py
  tests/unit/linking/test_link.py
  tests/unit/linking/test_mpi_service.py
  tests/unit/test_main.py
Labels: enhancement

#86 fix slack notifier open pulls
  .github/workflows/slack_notifier_open_pulls.yml
Labels: bug

#82 interfaces for configuring algorithms
  .github/pull_request_template.md
  pyproject.toml
  scripts/algorithm_config.py
  src/recordlinker/database.py
  src/recordlinker/linking/algorithm_service.py
  src/recordlinker/linking/link.py
  src/recordlinker/linking/matchers.py
  src/recordlinker/main.py
  src/recordlinker/routes/__init__.py
  src/recordlinker/routes/algorithm_router.py
  src/recordlinker/schemas/__init__.py
  src/recordlinker/schemas/algorithm.py
  src/recordlinker/schemas/pii.py
  src/recordlinker/utils.py
  tests/unit/conftest.py
  tests/unit/linking/test_algorithm_service.py
  tests/unit/linking/test_matchers.py
  tests/unit/routes/__init__.py
  tests/unit/routes/test_algorithm_router.py
  tests/unit/schemas/test_algorithm.py
  tests/unit/schemas/test_pii.py
  tests/unit/test_main.py
  tests/unit/test_utils.py
Labels: enhancement

#89 Auto initialize algorithms in DB
  .github/workflows/check_unit_tests.yml
  alembic.ini
  alembic/README.md
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/0c90faa0378f_create_algorithm_tables.py
  alembic/versions/6052c193a26a_add_blockingvalue_table.py
  alembic/versions/64ed9566f189_external_person_id_should_be_nullable.py
  alembic/versions/773a9759734c_redesign_mpi_schema.py
  alembic/versions/a30b8bbccfdf_add_dibbs_algorithms.py
  alembic/versions/ad18f1d41fad_convert_blockingkey_into_enum.py
  alembic/versions/bfbd015ca466_moving_externalperson_to_patient_table.py
  alembic/versions/d9eba1bdbad1_recreating_mpi_schema.py
  alembic/versions/f5716ac94693_dropping_mpi_schema.py
  assets/general/patient_resource_w_extensions.json
  assets/initial_algorithms.json
  assets/linking/basic_algorithm.json
  assets/linking/enhanced_algorithm.json
  assets/patient_bundle_to_link_with_mpi.json
  pyproject.toml
  scripts/local_server.sh
  src/recordlinker/config.py
  src/recordlinker/linking/algorithm_service.py
  src/recordlinker/linking/link.py
  src/recordlinker/log_config.yml
  src/recordlinker/main.py
  src/recordlinker/models/algorithm.py
  src/recordlinker/schemas/pii.py
  src/recordlinker/utils.py
  tests/unit/assets/initial_algorithms.json
  tests/unit/assets/patient_bundle.json
  tests/unit/assets/simple_patient_bundle_to_link_with_mpi.json
  tests/unit/conftest.py
  tests/unit/linking/test_link.py
  tests/unit/models/test_algorithm.py
  tests/unit/test_main.py
Labels: enhancement

#87 auto releases
  .github/release.yml
  .github/workflows/release.yml
  docs/releases.md
  scripts/next_tag.sh
Labels: enhancement, ops

#98 Bugfix for a ARG typo in the Dockerfile
  Dockerfile
Labels: bug

#100 add setting.db_table_prefix variable
  src/recordlinker/config.py
  src/recordlinker/models/algorithm.py
  src/recordlinker/models/base.py
  src/recordlinker/models/mpi.py
Labels: enhancement

#94 publishing docker images to ghcr.io on release
  .github/workflows/check_code_vulnerabilities.yml
  .github/workflows/check_lint.yml
  .github/workflows/check_unit_tests.yml
  .github/workflows/release.yml
  .github/workflows/slack_notifier_merged.yml
  .github/workflows/slack_notifier_open_pulls.yml
  .github/workflows/slack_notifier_review.yml
  Dockerfile
  compose.yml
  pyproject.toml
  src/recordlinker/linking/link.py
  src/recordlinker/utils.py
  tests/unit/test_utils.py
Labels: enhancement, ops

#88 Expand Feature Comparison Support
  docs/process_for_adding_feature.md
  src/recordlinker/linking/link.py
  src/recordlinker/linking/matchers.py
  src/recordlinker/schemas/pii.py
  tests/unit/linking/test_link.py
  tests/unit/schemas/test_pii.py
Labels: enhancement

#99 link router
  assets/sample_link_record_requests.json
  assets/sample_link_record_responses.json
  src/recordlinker/base_service.py
  src/recordlinker/main.py
  src/recordlinker/routes/link_router.py
  src/recordlinker/schemas/__init__.py
  src/recordlinker/schemas/link.py
  tests/unit/routes/test_link_router.py
  tests/unit/test_main.py
Labels: enhancement
