Repository CDCgov/RecordLinker, pull requests merged in 2024-11, with the labels that each got.

#116 Dockerfile Smoke Tests
  .github/workflows/check_smoke_tests.yml
  src/recordlinker/hl7/fhir.py
  src/recordlinker/linking/algorithm_service.py
  src/recordlinker/routes/link_router.py
  tests/performance/scripts/reset_db.sh
  tests/performance/scripts/send_linkage_requests.sh
  tests/unit/linking/test_algorithm_service.py
  tests/unit/routes/test_link_router.py
Labels: feature, automation

#136 bugfix: bulk insert serialization of data
  src/recordlinker/database/mpi_service.py
  src/recordlinker/models/mpi.py
  src/recordlinker/schemas/pii.py
  tests/unit/database/test_mpi_service.py
  tests/unit/routes/test_seed_router.py
Labels: bug

#141 Ability to delete a Patient record
  src/recordlinker/database/mpi_service.py
  src/recordlinker/routes/patient_router.py
  tests/unit/routes/test_patient_router.py
Labels: feature
