Repository CDCgov/RecordLinker, pull requests merged in 2024-09, with the labels that each got.

#12 feat(mpi): redesign mpi schema
  .env
  .gitignore
  alembic.ini
  alembic/README.md
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/6052c193a26a_add_blockingvalue_table.py
  alembic/versions/773a9759734c_redesign_mpi_schema.py
  pyproject.toml
  src/recordlinker/linkage/models.py
Labels: enhancement

#11 Adding workflows for unit tests and linting
  .github/dependabot.yml
  .github/workflows/check_code_vulnerabilities.yml
  .github/workflows/check_lint.yml
  .github/workflows/check_unit_tests.yml
  README.md
  pyproject.toml
  scripts/vulnerability_check.sh
  src/recordlinker/config.py
  src/recordlinker/linkage/config.py
  src/recordlinker/linkage/models.py
Labels: enhancement

#19 remove hardcoded test settings
  .env
  scripts/local_server.sh
  scripts/test_unit.sh
  src/recordlinker/config.py
  src/recordlinker/linkage/config.py
  src/recordlinker/linkage/mpi.py
  src/recordlinker/linkage/utils.py
  src/recordlinker/main.py
  src/recordlinker/utils.py
  tests/unit/test_dal.py
  tests/unit/test_linkage.py
  tests/unit/test_mpi.py
  tests/unit/test_mpi_utils.py
  tests/unit/test_record_linkage.py
  tests/unit/test_utils.py
Labels: enhancement

#27 update GH unit test workflow DB
  .github/workflows/check_unit_tests.yml
  pyproject.toml
Labels: bug

#20 seperating matching functions into its own module
  assets/linkage/dibbs_basic_algorithm.json
  assets/linkage/dibbs_enhanced_algorithm.json
  src/recordlinker/linkage/algorithms.py
  src/recordlinker/linkage/link.py
  src/recordlinker/linkage/matchers.py
  src/recordlinker/linkage/utils.py
  tests/unit/test_linkage.py
  tests/unit/test_linkage_utils.py
  tests/unit/test_matchers.py
Labels: enhancement

#31 Feat/algorithm configuration schema
  .env
  alembic/versions/0c90faa0378f_create_algorithm_tables.py
  src/recordlinker/linkage/models.py
  tests/unit/test_models.py
Labels: enhancement

#36 Reorganizing models
  alembic/env.py
  alembic/versions/0c90faa0378f_create_algorithm_tables.py
  alembic/versions/591a56cee781_.py
  alembic/versions/64ed9566f189_external_person_id_should_be_nullable.py
  alembic/versions/d9eba1bdbad1_recreating_mpi_schema.py
  alembic/versions/f5716ac94693_dropping_mpi_schema.py
  pyproject.toml
  src/recordlinker/config.py
  src/recordlinker/linkage/link.py
  src/recordlinker/linkage/matchers.py
  src/recordlinker/linkage/models.py
  src/recordlinker/linkage/utils.py
  src/recordlinker/linking/__init__.py
  src/recordlinker/linking/mpi_service.py
  src/recordlinker/models/__init__.py
  src/recordlinker/models/algorithm.py
  src/recordlinker/models/base.py
  src/recordlinker/models/mpi.py
  src/recordlinker/models/pii.py
  src/recordlinker/utils.py
  tests/unit/linking/__init__.py
  tests/unit/linking/test_mpi_service.py
  tests/unit/models/__init__.py
  tests/unit/models/test_algorithm.py
  tests/unit/models/test_mpi.py
  tests/unit/models/test_pii.py
  tests/unit/test_linkage_utils.py
  tests/unit/test_matchers.py
  tests/unit/test_models.py
  tests/unit/test_utils.py
Labels: enhancement

#50 [RL-25] Slack Notifications for reviews and merges
  .github/workflows/slack_notifier_merged.yaml
  .github/workflows/slack_notifier_review.yaml
Labels: ops

#51 Fix slack notifier merge emoji
  .github/workflows/slack_notifier_merged.yaml
Labels: ops

#35 feat: dibbs algorithm migrations
  alembic/versions/0c90faa0378f_create_algorithm_tables.py
  alembic/versions/591a56cee781_.py
  alembic/versions/a30b8bbccfdf_add_dibbs_algorithms.py
  alembic/versions/ad18f1d41fad_convert_blockingkey_into_enum.py
  alembic/versions/f5716ac94693_dropping_mpi_schema.py
Labels: enhancement
