Repository CDCgov/RecordLinker, pull requests merged in 2025-02, with the labels that each got.

#174 Patient Details Endpoints
  src/recordlinker/database/mpi_service.py
  src/recordlinker/routes/patient_router.py
  src/recordlinker/schemas/__init__.py
  src/recordlinker/schemas/mpi.py
  tests/unit/database/test_mpi_service.py
  tests/unit/routes/test_patient_router.py
Labels: feature

#191 new local scheme of dirty-tag for developer installation
  pyproject.toml
Labels: automation

#172 person cluster patient assignment endpoints
  src/recordlinker/database/mpi_service.py
  src/recordlinker/main.py
  src/recordlinker/routes/patient_router.py
  src/recordlinker/routes/person_router.py
  src/recordlinker/schemas/__init__.py
  src/recordlinker/schemas/mpi.py
  tests/unit/database/test_mpi_service.py
  tests/unit/routes/test_person_router.py
Labels: feature

#210 compare the entire GIVEN_NAME
  docs/site/reference.md
  src/recordlinker/schemas/pii.py
  tests/unit/linking/test_matchers.py
  tests/unit/schemas/test_pii.py
Labels: bug

#206 patient / person API endpoints for retrieving data
  src/recordlinker/database/mpi_service.py
  src/recordlinker/routes/patient_router.py
  src/recordlinker/routes/person_router.py
  src/recordlinker/schemas/__init__.py
  src/recordlinker/schemas/mpi.py
  tests/unit/conftest.py
  tests/unit/database/test_mpi_service.py
  tests/unit/routes/test_patient_router.py
  tests/unit/routes/test_person_router.py
Labels: feature

#216 add custom api docs template to address a11y issues
  docs/api_template.hbs
  scripts/build_docs.sh
Labels: a11y

#228 minor updates to README
  README.md
Labels: documentation

#227 Removed first 2 chars of authority from IDENTIFIER blocking key
  docs/site/reference.md
  src/recordlinker/schemas/pii.py
  tests/unit/schemas/test_pii.py
Labels: feature
